### ISSUE TITLE
Guidance on installing `espeak-ng`

### ISSUE THREAD

**Issue by brresnic** [sciforce/phones-las#23]
Hi sciforce! This repo looks really nice.

I'm having trouble running this code with TIMIT and, in particular, with configuring the `espeak-ng` dependency.  

Could you add a line to the readme on installing `espeak-ng`? Does this dependency even support mac?

**Comment by akademi4eg** [comment]
@IvanHahan could you please check on Mac if `espeak-ng` gets installed properly and update `README.md` file?

**Comment by akademi4eg** [comment]
Hi @brresnic ,
The most recent PR #24 adds a summary on espeak-ng installation.
@IvanHahan checked on his Mac and it works fine now.

Let us know if you have any issues or questions.
